// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// hello
RcppExport SEXP hello(SEXP a);
RcppExport SEXP fakepackage_hello(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    __result = Rcpp::wrap(hello(a));
    return __result;
END_RCPP
}
